<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1\GetFavoriteGroupsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Избранная группа
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetFavoriteGroupsResponse.FavoriteGroup</code>
 */
class FavoriteGroup extends \Google\Protobuf\Internal\Message
{
    /**
     *Уникальный идентификатор группы.
     *
     * Generated from protobuf field <code>string group_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $group_id = '';
    /**
     *Название группы.
     *
     * Generated from protobuf field <code>string group_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $group_name = '';
    /**
     *Цвет группы в HEX-формате.
     *
     * Generated from protobuf field <code>string color = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $color = '';
    /**
     *Количество инструментов в группе.
     *
     * Generated from protobuf field <code>int32 size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $size = 0;
    /**
     *Признак наличия в группе хотя бы одного инструмента из запроса.
     *
     * Generated from protobuf field <code>optional bool contains_instrument = 5;</code>
     */
    protected $contains_instrument = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $group_id
     *          Уникальный идентификатор группы.
     *     @type string $group_name
     *          Название группы.
     *     @type string $color
     *          Цвет группы в HEX-формате.
     *     @type int $size
     *          Количество инструментов в группе.
     *     @type bool $contains_instrument
     *          Признак наличия в группе хотя бы одного инструмента из запроса.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Уникальный идентификатор группы.
     *
     * Generated from protobuf field <code>string group_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *Уникальный идентификатор группы.
     *
     * Generated from protobuf field <code>string group_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     *Название группы.
     *
     * Generated from protobuf field <code>string group_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     *Название группы.
     *
     * Generated from protobuf field <code>string group_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

    /**
     *Цвет группы в HEX-формате.
     *
     * Generated from protobuf field <code>string color = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     *Цвет группы в HEX-формате.
     *
     * Generated from protobuf field <code>string color = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->color = $var;

        return $this;
    }

    /**
     *Количество инструментов в группе.
     *
     * Generated from protobuf field <code>int32 size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     *Количество инструментов в группе.
     *
     * Generated from protobuf field <code>int32 size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     *Признак наличия в группе хотя бы одного инструмента из запроса.
     *
     * Generated from protobuf field <code>optional bool contains_instrument = 5;</code>
     * @return bool
     */
    public function getContainsInstrument()
    {
        return isset($this->contains_instrument) ? $this->contains_instrument : false;
    }

    public function hasContainsInstrument()
    {
        return isset($this->contains_instrument);
    }

    public function clearContainsInstrument()
    {
        unset($this->contains_instrument);
    }

    /**
     *Признак наличия в группе хотя бы одного инструмента из запроса.
     *
     * Generated from protobuf field <code>optional bool contains_instrument = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setContainsInstrument($var)
    {
        GPBUtil::checkBool($var);
        $this->contains_instrument = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FavoriteGroup::class, \Tinkoff\Invest\V1\GetFavoriteGroupsResponse_FavoriteGroup::class);

