<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1\RiskRatesResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.RiskRatesResponse.RiskRate</code>
 */
class RiskRate extends \Google\Protobuf\Internal\Message
{
    /**
     * Категория риска.
     *
     * Generated from protobuf field <code>string risk_level_code = 2;</code>
     */
    protected $risk_level_code = '';
    /**
     * Значение ставки риска.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation value = 5;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $risk_level_code
     *           Категория риска.
     *     @type \Tinkoff\Invest\V1\Quotation $value
     *           Значение ставки риска.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Категория риска.
     *
     * Generated from protobuf field <code>string risk_level_code = 2;</code>
     * @return string
     */
    public function getRiskLevelCode()
    {
        return $this->risk_level_code;
    }

    /**
     * Категория риска.
     *
     * Generated from protobuf field <code>string risk_level_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRiskLevelCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->risk_level_code = $var;

        return $this;
    }

    /**
     * Значение ставки риска.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation value = 5;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Значение ставки риска.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation value = 5;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RiskRate::class, \Tinkoff\Invest\V1\RiskRatesResponse_RiskRate::class);

