<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1\StructuredNote;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Доходность.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.StructuredNote.Yield</code>
 */
class Yield extends \Google\Protobuf\Internal\Message
{
    /**
     *Тип доходности.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StructuredNote.YieldType type = 1;</code>
     */
    protected $type = 0;
    /**
     *Значение доходности.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation value = 2;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *          Тип доходности.
     *     @type \Tinkoff\Invest\V1\Quotation $value
     *          Значение доходности.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Тип доходности.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StructuredNote.YieldType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *Тип доходности.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StructuredNote.YieldType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\StructuredNote\YieldType::class);
        $this->type = $var;

        return $this;
    }

    /**
     *Значение доходности.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation value = 2;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getValue()
    {
        return isset($this->value) ? $this->value : null;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     *Значение доходности.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation value = 2;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Yield::class, \Tinkoff\Invest\V1\StructuredNote_Yield::class);

