<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Tinkoff\Invest\V1\GetOrdersRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetOrdersRequest.GetOrdersRequestFilters</code>
 */
class GetOrdersRequestFilters extends \Google\Protobuf\Internal\Message
{
    /**
     *Дата и время, начиная с которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp from = 1;</code>
     */
    protected $from = null;
    /**
     *Дата и время, до которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp to = 2;</code>
     */
    protected $to = null;
    /**
     *Статусы заявок.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.OrderExecutionReportStatus execution_status = 3;</code>
     */
    private $execution_status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $from
     *          Дата и время, начиная с которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *     @type \Google\Protobuf\Timestamp $to
     *          Дата и время, до которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $execution_status
     *          Статусы заявок.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     *Дата и время, начиная с которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp from = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFrom()
    {
        return $this->from;
    }

    public function hasFrom()
    {
        return isset($this->from);
    }

    public function clearFrom()
    {
        unset($this->from);
    }

    /**
     *Дата и время, начиная с которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp from = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->from = $var;

        return $this;
    }

    /**
     *Дата и время, до которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp to = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTo()
    {
        return $this->to;
    }

    public function hasTo()
    {
        return isset($this->to);
    }

    public function clearTo()
    {
        unset($this->to);
    }

    /**
     *Дата и время, до которой нужно получить информацию в часовом поясе UTC. Параметр применим только к ордерам, созданным сегодня.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp to = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->to = $var;

        return $this;
    }

    /**
     *Статусы заявок.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.OrderExecutionReportStatus execution_status = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExecutionStatus()
    {
        return $this->execution_status;
    }

    /**
     *Статусы заявок.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.OrderExecutionReportStatus execution_status = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExecutionStatus($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Tinkoff\Invest\V1\OrderExecutionReportStatus::class);
        $this->execution_status = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(GetOrdersRequestFilters::class, \Tinkoff\Invest\V1\GetOrdersRequest_GetOrdersRequestFilters::class);

