<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Список активов.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.AssetsResponse</code>
 */
class AssetsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Активы.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Asset assets = 1;</code>
     */
    private $assets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\Asset[]|\Google\Protobuf\Internal\RepeatedField $assets
     *          Активы.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Активы.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Asset assets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAssets()
    {
        return $this->assets;
    }

    /**
     *Активы.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Asset assets = 1;</code>
     * @param \Tinkoff\Invest\V1\Asset[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAssets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\Asset::class);
        $this->assets = $arr;

        return $this;
    }

}

