<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketdata.proto

namespace Tinkoff\Invest\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>tinkoff.public.invest.api.contract.v1.CandleSource</code>
 */
class CandleSource
{
    /**
     *Источник свечей не определён.
     *
     * Generated from protobuf enum <code>CANDLE_SOURCE_UNSPECIFIED = 0;</code>
     */
    const CANDLE_SOURCE_UNSPECIFIED = 0;
    /**
     *Биржевые свечи.
     *
     * Generated from protobuf enum <code>CANDLE_SOURCE_EXCHANGE = 1;</code>
     */
    const CANDLE_SOURCE_EXCHANGE = 1;
    /**
     *Свечи  дилера в результате торговли по выходным.
     *
     * Generated from protobuf enum <code>CANDLE_SOURCE_DEALER_WEEKEND = 2;</code>
     */
    const CANDLE_SOURCE_DEALER_WEEKEND = 2;

    private static $valueToName = [
        self::CANDLE_SOURCE_UNSPECIFIED => 'CANDLE_SOURCE_UNSPECIFIED',
        self::CANDLE_SOURCE_EXCHANGE => 'CANDLE_SOURCE_EXCHANGE',
        self::CANDLE_SOURCE_DEALER_WEEKEND => 'CANDLE_SOURCE_DEALER_WEEKEND',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

