<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Данные о стране.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.CountryResponse</code>
 */
class CountryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Двухбуквенный код страны.
     *
     * Generated from protobuf field <code>string alfa_two = 1;</code>
     */
    protected $alfa_two = '';
    /**
     *Трёхбуквенный код страны.
     *
     * Generated from protobuf field <code>string alfa_three = 2;</code>
     */
    protected $alfa_three = '';
    /**
     *Наименование страны.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     *Краткое наименование страны.
     *
     * Generated from protobuf field <code>string name_brief = 4;</code>
     */
    protected $name_brief = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alfa_two
     *          Двухбуквенный код страны.
     *     @type string $alfa_three
     *          Трёхбуквенный код страны.
     *     @type string $name
     *          Наименование страны.
     *     @type string $name_brief
     *          Краткое наименование страны.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Двухбуквенный код страны.
     *
     * Generated from protobuf field <code>string alfa_two = 1;</code>
     * @return string
     */
    public function getAlfaTwo()
    {
        return $this->alfa_two;
    }

    /**
     *Двухбуквенный код страны.
     *
     * Generated from protobuf field <code>string alfa_two = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAlfaTwo($var)
    {
        GPBUtil::checkString($var, True);
        $this->alfa_two = $var;

        return $this;
    }

    /**
     *Трёхбуквенный код страны.
     *
     * Generated from protobuf field <code>string alfa_three = 2;</code>
     * @return string
     */
    public function getAlfaThree()
    {
        return $this->alfa_three;
    }

    /**
     *Трёхбуквенный код страны.
     *
     * Generated from protobuf field <code>string alfa_three = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlfaThree($var)
    {
        GPBUtil::checkString($var, True);
        $this->alfa_three = $var;

        return $this;
    }

    /**
     *Наименование страны.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *Наименование страны.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *Краткое наименование страны.
     *
     * Generated from protobuf field <code>string name_brief = 4;</code>
     * @return string
     */
    public function getNameBrief()
    {
        return $this->name_brief;
    }

    /**
     *Краткое наименование страны.
     *
     * Generated from protobuf field <code>string name_brief = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNameBrief($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_brief = $var;

        return $this;
    }

}

