<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.CreateFavoriteGroupResponse</code>
 */
class CreateFavoriteGroupResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Уникальный идентификатор группы.
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     */
    protected $group_id = '';
    /**
     *Название группы.
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     */
    protected $group_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $group_id
     *          Уникальный идентификатор группы.
     *     @type string $group_name
     *          Название группы.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Уникальный идентификатор группы.
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *Уникальный идентификатор группы.
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     *Название группы.
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     *Название группы.
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

}

