<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operations.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Отчет «Справка о доходах за пределами РФ».
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.DividendsForeignIssuerReport</code>
 */
class DividendsForeignIssuerReport extends \Google\Protobuf\Internal\Message
{
    /**
     *Дата фиксации реестра.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp record_date = 1;</code>
     */
    protected $record_date = null;
    /**
     *Дата выплаты.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp payment_date = 2;</code>
     */
    protected $payment_date = null;
    /**
     *Наименование ценной бумаги.
     *
     * Generated from protobuf field <code>string security_name = 3;</code>
     */
    protected $security_name = '';
    /**
     *ISIN-идентификатор ценной бумаги.
     *
     * Generated from protobuf field <code>string isin = 4;</code>
     */
    protected $isin = '';
    /**
     *Страна эмитента. Для депозитарных расписок указывается страна эмитента базового актива.
     *
     * Generated from protobuf field <code>string issuer_country = 5;</code>
     */
    protected $issuer_country = '';
    /**
     *Количество ценных бумаг.
     *
     * Generated from protobuf field <code>int64 quantity = 6;</code>
     */
    protected $quantity = 0;
    /**
     *Выплаты на одну бумагу
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend = 7;</code>
     */
    protected $dividend = null;
    /**
     *Комиссия внешних платежных агентов.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation external_commission = 8;</code>
     */
    protected $external_commission = null;
    /**
     *Сумма до удержания налога.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend_gross = 9;</code>
     */
    protected $dividend_gross = null;
    /**
     *Сумма налога, удержанного агентом.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation tax = 10;</code>
     */
    protected $tax = null;
    /**
     *Итоговая сумма выплаты.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend_amount = 11;</code>
     */
    protected $dividend_amount = null;
    /**
     *Валюта.
     *
     * Generated from protobuf field <code>string currency = 12;</code>
     */
    protected $currency = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $record_date
     *          Дата фиксации реестра.
     *     @type \Google\Protobuf\Timestamp $payment_date
     *          Дата выплаты.
     *     @type string $security_name
     *          Наименование ценной бумаги.
     *     @type string $isin
     *          ISIN-идентификатор ценной бумаги.
     *     @type string $issuer_country
     *          Страна эмитента. Для депозитарных расписок указывается страна эмитента базового актива.
     *     @type int|string $quantity
     *          Количество ценных бумаг.
     *     @type \Tinkoff\Invest\V1\Quotation $dividend
     *          Выплаты на одну бумагу
     *     @type \Tinkoff\Invest\V1\Quotation $external_commission
     *          Комиссия внешних платежных агентов.
     *     @type \Tinkoff\Invest\V1\Quotation $dividend_gross
     *          Сумма до удержания налога.
     *     @type \Tinkoff\Invest\V1\Quotation $tax
     *          Сумма налога, удержанного агентом.
     *     @type \Tinkoff\Invest\V1\Quotation $dividend_amount
     *          Итоговая сумма выплаты.
     *     @type string $currency
     *          Валюта.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     *Дата фиксации реестра.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp record_date = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getRecordDate()
    {
        return $this->record_date;
    }

    public function hasRecordDate()
    {
        return isset($this->record_date);
    }

    public function clearRecordDate()
    {
        unset($this->record_date);
    }

    /**
     *Дата фиксации реестра.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp record_date = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setRecordDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->record_date = $var;

        return $this;
    }

    /**
     *Дата выплаты.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp payment_date = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getPaymentDate()
    {
        return $this->payment_date;
    }

    public function hasPaymentDate()
    {
        return isset($this->payment_date);
    }

    public function clearPaymentDate()
    {
        unset($this->payment_date);
    }

    /**
     *Дата выплаты.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp payment_date = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setPaymentDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->payment_date = $var;

        return $this;
    }

    /**
     *Наименование ценной бумаги.
     *
     * Generated from protobuf field <code>string security_name = 3;</code>
     * @return string
     */
    public function getSecurityName()
    {
        return $this->security_name;
    }

    /**
     *Наименование ценной бумаги.
     *
     * Generated from protobuf field <code>string security_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSecurityName($var)
    {
        GPBUtil::checkString($var, True);
        $this->security_name = $var;

        return $this;
    }

    /**
     *ISIN-идентификатор ценной бумаги.
     *
     * Generated from protobuf field <code>string isin = 4;</code>
     * @return string
     */
    public function getIsin()
    {
        return $this->isin;
    }

    /**
     *ISIN-идентификатор ценной бумаги.
     *
     * Generated from protobuf field <code>string isin = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIsin($var)
    {
        GPBUtil::checkString($var, True);
        $this->isin = $var;

        return $this;
    }

    /**
     *Страна эмитента. Для депозитарных расписок указывается страна эмитента базового актива.
     *
     * Generated from protobuf field <code>string issuer_country = 5;</code>
     * @return string
     */
    public function getIssuerCountry()
    {
        return $this->issuer_country;
    }

    /**
     *Страна эмитента. Для депозитарных расписок указывается страна эмитента базового актива.
     *
     * Generated from protobuf field <code>string issuer_country = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIssuerCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->issuer_country = $var;

        return $this;
    }

    /**
     *Количество ценных бумаг.
     *
     * Generated from protobuf field <code>int64 quantity = 6;</code>
     * @return int|string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     *Количество ценных бумаг.
     *
     * Generated from protobuf field <code>int64 quantity = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     *Выплаты на одну бумагу
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend = 7;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getDividend()
    {
        return $this->dividend;
    }

    public function hasDividend()
    {
        return isset($this->dividend);
    }

    public function clearDividend()
    {
        unset($this->dividend);
    }

    /**
     *Выплаты на одну бумагу
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend = 7;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setDividend($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->dividend = $var;

        return $this;
    }

    /**
     *Комиссия внешних платежных агентов.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation external_commission = 8;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getExternalCommission()
    {
        return $this->external_commission;
    }

    public function hasExternalCommission()
    {
        return isset($this->external_commission);
    }

    public function clearExternalCommission()
    {
        unset($this->external_commission);
    }

    /**
     *Комиссия внешних платежных агентов.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation external_commission = 8;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setExternalCommission($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->external_commission = $var;

        return $this;
    }

    /**
     *Сумма до удержания налога.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend_gross = 9;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getDividendGross()
    {
        return $this->dividend_gross;
    }

    public function hasDividendGross()
    {
        return isset($this->dividend_gross);
    }

    public function clearDividendGross()
    {
        unset($this->dividend_gross);
    }

    /**
     *Сумма до удержания налога.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend_gross = 9;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setDividendGross($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->dividend_gross = $var;

        return $this;
    }

    /**
     *Сумма налога, удержанного агентом.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation tax = 10;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getTax()
    {
        return $this->tax;
    }

    public function hasTax()
    {
        return isset($this->tax);
    }

    public function clearTax()
    {
        unset($this->tax);
    }

    /**
     *Сумма налога, удержанного агентом.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation tax = 10;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setTax($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->tax = $var;

        return $this;
    }

    /**
     *Итоговая сумма выплаты.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend_amount = 11;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getDividendAmount()
    {
        return $this->dividend_amount;
    }

    public function hasDividendAmount()
    {
        return isset($this->dividend_amount);
    }

    public function clearDividendAmount()
    {
        unset($this->dividend_amount);
    }

    /**
     *Итоговая сумма выплаты.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation dividend_amount = 11;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setDividendAmount($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->dividend_amount = $var;

        return $this;
    }

    /**
     *Валюта.
     *
     * Generated from protobuf field <code>string currency = 12;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     *Валюта.
     *
     * Generated from protobuf field <code>string currency = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

}

