<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Данные по фондам.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.EtfsResponse</code>
 */
class EtfsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Массив фондов.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Etf instruments = 1;</code>
     */
    private $instruments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\Etf[] $instruments
     *          Массив фондов.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Массив фондов.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Etf instruments = 1;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\Etf>
     */
    public function getInstruments()
    {
        return $this->instruments;
    }

    /**
     *Массив фондов.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Etf instruments = 1;</code>
     * @param \Tinkoff\Invest\V1\Etf[] $var
     * @return $this
     */
    public function setInstruments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\Etf::class);
        $this->instruments = $arr;

        return $this;
    }

}

