<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stoporders.proto

namespace Tinkoff\Invest\V1;

use UnexpectedValueException;

/**
 *Тип выставляемой заявки.
 *
 * Protobuf type <code>tinkoff.public.invest.api.contract.v1.ExchangeOrderType</code>
 */
class ExchangeOrderType
{
    /**
     *Значение не указано
     *
     * Generated from protobuf enum <code>EXCHANGE_ORDER_TYPE_UNSPECIFIED = 0;</code>
     */
    const EXCHANGE_ORDER_TYPE_UNSPECIFIED = 0;
    /**
     *Заявка по рыночной цене
     *
     * Generated from protobuf enum <code>EXCHANGE_ORDER_TYPE_MARKET = 1;</code>
     */
    const EXCHANGE_ORDER_TYPE_MARKET = 1;
    /**
     *Лимитная заявка
     *
     * Generated from protobuf enum <code>EXCHANGE_ORDER_TYPE_LIMIT = 2;</code>
     */
    const EXCHANGE_ORDER_TYPE_LIMIT = 2;

    private static $valueToName = [
        self::EXCHANGE_ORDER_TYPE_UNSPECIFIED => 'EXCHANGE_ORDER_TYPE_UNSPECIFIED',
        self::EXCHANGE_ORDER_TYPE_MARKET => 'EXCHANGE_ORDER_TYPE_MARKET',
        self::EXCHANGE_ORDER_TYPE_LIMIT => 'EXCHANGE_ORDER_TYPE_LIMIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

