<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *События по облигации.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetBondEventsRequest</code>
 */
class GetBondEventsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Начало запрашиваемого периода по UTC.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp from = 2;</code>
     */
    protected $from = null;
    /**
     *Окончание запрашиваемого периода по UTC.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp to = 3;</code>
     */
    protected $to = null;
    /**
     *Идентификатор инструмента — `figi` или `instrument_uid`.
     *
     * Generated from protobuf field <code>string instrument_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instrument_id = '';
    /**
     *Тип события
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.GetBondEventsRequest.EventType type = 5;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $from
     *          Начало запрашиваемого периода по UTC.
     *     @type \Google\Protobuf\Timestamp $to
     *          Окончание запрашиваемого периода по UTC.
     *     @type string $instrument_id
     *          Идентификатор инструмента — `figi` или `instrument_uid`.
     *     @type int $type
     *          Тип события
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Начало запрашиваемого периода по UTC.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp from = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFrom()
    {
        return $this->from;
    }

    public function hasFrom()
    {
        return isset($this->from);
    }

    public function clearFrom()
    {
        unset($this->from);
    }

    /**
     *Начало запрашиваемого периода по UTC.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp from = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->from = $var;

        return $this;
    }

    /**
     *Окончание запрашиваемого периода по UTC.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp to = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTo()
    {
        return $this->to;
    }

    public function hasTo()
    {
        return isset($this->to);
    }

    public function clearTo()
    {
        unset($this->to);
    }

    /**
     *Окончание запрашиваемого периода по UTC.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp to = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->to = $var;

        return $this;
    }

    /**
     *Идентификатор инструмента — `figi` или `instrument_uid`.
     *
     * Generated from protobuf field <code>string instrument_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getInstrumentId()
    {
        return $this->instrument_id;
    }

    /**
     *Идентификатор инструмента — `figi` или `instrument_uid`.
     *
     * Generated from protobuf field <code>string instrument_id = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setInstrumentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->instrument_id = $var;

        return $this;
    }

    /**
     *Тип события
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.GetBondEventsRequest.EventType type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *Тип события
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.GetBondEventsRequest.EventType type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\GetBondEventsRequest\EventType::class);
        $this->type = $var;

        return $this;
    }

}

