<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

if (false) {
    /**
     * This class is deprecated. Use Tinkoff\Invest\V1\GetBondEventsResponse\BondEvent instead.
     * @deprecated
     */
    class GetBondEventsResponse_BondEvent {}
}
class_exists(GetBondEventsResponse\BondEvent::class);
@trigger_error('Tinkoff\Invest\V1\GetBondEventsResponse_BondEvent is deprecated and will be removed in the next major release. Use Tinkoff\Invest\V1\GetBondEventsResponse\BondEvent instead', E_USER_DEPRECATED);

