<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Консенсус-прогнозы
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetConsensusForecastsResponse</code>
 */
class GetConsensusForecastsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Массив прогнозов
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.GetConsensusForecastsResponse.ConsensusForecastsItem items = 1;</code>
     */
    private $items;
    /**
     *Данные по пагинации
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PageResponse page = 2;</code>
     */
    protected $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\GetConsensusForecastsResponse\ConsensusForecastsItem[]|\Google\Protobuf\Internal\RepeatedField $items
     *           Массив прогнозов
     *     @type \Tinkoff\Invest\V1\PageResponse $page
     *          Данные по пагинации
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Массив прогнозов
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.GetConsensusForecastsResponse.ConsensusForecastsItem items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Массив прогнозов
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.GetConsensusForecastsResponse.ConsensusForecastsItem items = 1;</code>
     * @param \Tinkoff\Invest\V1\GetConsensusForecastsResponse\ConsensusForecastsItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\GetConsensusForecastsResponse\ConsensusForecastsItem::class);
        $this->items = $arr;

        return $this;
    }

    /**
     *Данные по пагинации
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PageResponse page = 2;</code>
     * @return \Tinkoff\Invest\V1\PageResponse|null
     */
    public function getPage()
    {
        return isset($this->page) ? $this->page : null;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     *Данные по пагинации
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PageResponse page = 2;</code>
     * @param \Tinkoff\Invest\V1\PageResponse $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\PageResponse::class);
        $this->page = $var;

        return $this;
    }

}

