<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketdata.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Список свечей.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetCandlesResponse</code>
 */
class GetCandlesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Массив свечей.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.HistoricCandle candles = 1;</code>
     */
    private $candles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\HistoricCandle[] $candles
     *          Массив свечей.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Marketdata::initOnce();
        parent::__construct($data);
    }

    /**
     *Массив свечей.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.HistoricCandle candles = 1;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\HistoricCandle>
     */
    public function getCandles()
    {
        return $this->candles;
    }

    /**
     *Массив свечей.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.HistoricCandle candles = 1;</code>
     * @param \Tinkoff\Invest\V1\HistoricCandle[] $var
     * @return $this
     */
    public function setCandles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\HistoricCandle::class);
        $this->candles = $arr;

        return $this;
    }

}

