<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Дивиденды.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetDividendsResponse</code>
 */
class GetDividendsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Dividend dividends = 1;</code>
     */
    private $dividends;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\Dividend[] $dividends
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Dividend dividends = 1;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\Dividend>
     */
    public function getDividends()
    {
        return $this->dividends;
    }

    /**
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.Dividend dividends = 1;</code>
     * @param \Tinkoff\Invest\V1\Dividend[] $var
     * @return $this
     */
    public function setDividends($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\Dividend::class);
        $this->dividends = $arr;

        return $this;
    }

}

