<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Избранные группы
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetFavoriteGroupsResponse</code>
 */
class GetFavoriteGroupsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Массив групп избранных списков инструментов.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.GetFavoriteGroupsResponse.FavoriteGroup groups = 1;</code>
     */
    private $groups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\GetFavoriteGroupsResponse\FavoriteGroup[] $groups
     *          Массив групп избранных списков инструментов.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     *Массив групп избранных списков инструментов.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.GetFavoriteGroupsResponse.FavoriteGroup groups = 1;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\GetFavoriteGroupsResponse\FavoriteGroup>
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     *Массив групп избранных списков инструментов.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.GetFavoriteGroupsResponse.FavoriteGroup groups = 1;</code>
     * @param \Tinkoff\Invest\V1\GetFavoriteGroupsResponse\FavoriteGroup[] $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\GetFavoriteGroupsResponse\FavoriteGroup::class);
        $this->groups = $arr;

        return $this;
    }

}

