<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketdata.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Список цен последних сделок.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetLastPricesResponse</code>
 */
class GetLastPricesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Массив цен последних сделок.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.LastPrice last_prices = 1;</code>
     */
    private $last_prices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\LastPrice[] $last_prices
     *          Массив цен последних сделок.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Marketdata::initOnce();
        parent::__construct($data);
    }

    /**
     *Массив цен последних сделок.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.LastPrice last_prices = 1;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\LastPrice>
     */
    public function getLastPrices()
    {
        return $this->last_prices;
    }

    /**
     *Массив цен последних сделок.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.LastPrice last_prices = 1;</code>
     * @param \Tinkoff\Invest\V1\LastPrice[] $var
     * @return $this
     */
    public function setLastPrices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\LastPrice::class);
        $this->last_prices = $arr;

        return $this;
    }

}

