<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketdata.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetMarketValuesResponse</code>
 */
class GetMarketValuesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Массив значений параметров.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.MarketValueInstrument instruments = 1;</code>
     */
    private $instruments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Tinkoff\Invest\V1\MarketValueInstrument>|\Google\Protobuf\Internal\RepeatedField $instruments
     *          Массив значений параметров.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Marketdata::initOnce();
        parent::__construct($data);
    }

    /**
     *Массив значений параметров.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.MarketValueInstrument instruments = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInstruments()
    {
        return $this->instruments;
    }

    /**
     *Массив значений параметров.
     *
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.MarketValueInstrument instruments = 1;</code>
     * @param array<\Tinkoff\Invest\V1\MarketValueInstrument>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInstruments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\MarketValueInstrument::class);
        $this->instruments = $arr;

        return $this;
    }

}

