<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Запрос получения статуса торгового поручения.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetOrderStateRequest</code>
 */
class GetOrderStateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Номер счета.
     *
     * Generated from protobuf field <code>string account_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $account_id = '';
    /**
     *Идентификатор заявки.
     *
     * Generated from protobuf field <code>string order_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $order_id = '';
    /**
     *Тип цены.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 3;</code>
     */
    protected $price_type = 0;
    /**
     *Тип идентификатора заявки.
     *
     * Generated from protobuf field <code>optional .tinkoff.public.invest.api.contract.v1.OrderIdType order_id_type = 4;</code>
     */
    protected $order_id_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_id
     *          Номер счета.
     *     @type string $order_id
     *          Идентификатор заявки.
     *     @type int $price_type
     *          Тип цены.
     *     @type int $order_id_type
     *          Тип идентификатора заявки.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     *Номер счета.
     *
     * Generated from protobuf field <code>string account_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     *Номер счета.
     *
     * Generated from protobuf field <code>string account_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     *Идентификатор заявки.
     *
     * Generated from protobuf field <code>string order_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     *Идентификатор заявки.
     *
     * Generated from protobuf field <code>string order_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     *Тип цены.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 3;</code>
     * @return int
     */
    public function getPriceType()
    {
        return $this->price_type;
    }

    /**
     *Тип цены.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPriceType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\PriceType::class);
        $this->price_type = $var;

        return $this;
    }

    /**
     *Тип идентификатора заявки.
     *
     * Generated from protobuf field <code>optional .tinkoff.public.invest.api.contract.v1.OrderIdType order_id_type = 4;</code>
     * @return int
     */
    public function getOrderIdType()
    {
        return isset($this->order_id_type) ? $this->order_id_type : 0;
    }

    public function hasOrderIdType()
    {
        return isset($this->order_id_type);
    }

    public function clearOrderIdType()
    {
        unset($this->order_id_type);
    }

    /**
     *Тип идентификатора заявки.
     *
     * Generated from protobuf field <code>optional .tinkoff.public.invest.api.contract.v1.OrderIdType order_id_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderIdType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\OrderIdType::class);
        $this->order_id_type = $var;

        return $this;
    }

}

