<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Tinkoff\Invest\V1;

if (false) {
    /**
     * This class is deprecated. Use Tinkoff\Invest\V1\GetOrderPriceResponse\ExtraFuture instead.
     * @deprecated
     */
    class GetOrderPriceResponse_ExtraFuture {}
}
class_exists(GetOrderPriceResponse\ExtraFuture::class);
@trigger_error('Tinkoff\Invest\V1\GetOrderPriceResponse_ExtraFuture is deprecated and will be removed in the next major release. Use Tinkoff\Invest\V1\GetOrderPriceResponse\ExtraFuture instead', E_USER_DEPRECATED);

