<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Запрос получения статуса торгового поручения.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.GetOrderStateRequest</code>
 */
class GetOrderStateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Номер счёта.
     *
     * Generated from protobuf field <code>string account_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $account_id = '';
    /**
     *Идентификатор заявки.
     *
     * Generated from protobuf field <code>string order_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $order_id = '';
    /**
     *Тип цены.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 3;</code>
     */
    protected $price_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_id
     *          Номер счёта.
     *     @type string $order_id
     *          Идентификатор заявки.
     *     @type int $price_type
     *          Тип цены.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     *Номер счёта.
     *
     * Generated from protobuf field <code>string account_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     *Номер счёта.
     *
     * Generated from protobuf field <code>string account_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     *Идентификатор заявки.
     *
     * Generated from protobuf field <code>string order_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     *Идентификатор заявки.
     *
     * Generated from protobuf field <code>string order_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     *Тип цены.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 3;</code>
     * @return int
     */
    public function getPriceType()
    {
        return $this->price_type;
    }

    /**
     *Тип цены.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPriceType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\PriceType::class);
        $this->price_type = $var;

        return $this;
    }

}

