<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketdata.proto

namespace Tinkoff\Invest\V1;

if (false) {
    /**
     * This class is deprecated. Use Tinkoff\Invest\V1\GetTechAnalysisRequest\TypeOfPrice instead.
     * @deprecated
     */
    class GetTechAnalysisRequest_TypeOfPrice {}
}
class_exists(GetTechAnalysisRequest\TypeOfPrice::class);
@trigger_error('Tinkoff\Invest\V1\GetTechAnalysisRequest_TypeOfPrice is deprecated and will be removed in the next major release. Use Tinkoff\Invest\V1\GetTechAnalysisRequest\TypeOfPrice instead', E_USER_DEPRECATED);

