<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Индикатив
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.IndicativeResponse</code>
 */
class IndicativeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Figi-идентификатор инструмента
     *
     * Generated from protobuf field <code>string figi = 1;</code>
     */
    protected $figi = '';
    /**
     * Тикер инструмента
     *
     * Generated from protobuf field <code>string ticker = 2;</code>
     */
    protected $ticker = '';
    /**
     * Класс-код инструмента
     *
     * Generated from protobuf field <code>string class_code = 3;</code>
     */
    protected $class_code = '';
    /**
     * Валюта расчётов
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     */
    protected $currency = '';
    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentType instrument_kind = 10;</code>
     */
    protected $instrument_kind = 0;
    /**
     * Название инструмента
     *
     * Generated from protobuf field <code>string name = 12;</code>
     */
    protected $name = '';
    /**
     * Tорговая площадка (секция биржи)
     *
     * Generated from protobuf field <code>string exchange = 13;</code>
     */
    protected $exchange = '';
    /**
     * Уникальный идентификатор инструмента
     *
     * Generated from protobuf field <code>string uid = 14;</code>
     */
    protected $uid = '';
    /**
     * Признак доступности для покупки
     *
     * Generated from protobuf field <code>bool buy_available_flag = 404;</code>
     */
    protected $buy_available_flag = false;
    /**
     * Признак доступности для продажи
     *
     * Generated from protobuf field <code>bool sell_available_flag = 405;</code>
     */
    protected $sell_available_flag = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $figi
     *           Figi-идентификатор инструмента
     *     @type string $ticker
     *           Тикер инструмента
     *     @type string $class_code
     *           Класс-код инструмента
     *     @type string $currency
     *           Валюта расчётов
     *     @type int $instrument_kind
     *          Тип инструмента.
     *     @type string $name
     *           Название инструмента
     *     @type string $exchange
     *           Tорговая площадка (секция биржи)
     *     @type string $uid
     *           Уникальный идентификатор инструмента
     *     @type bool $buy_available_flag
     *           Признак доступности для покупки
     *     @type bool $sell_available_flag
     *           Признак доступности для продажи
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Figi-идентификатор инструмента
     *
     * Generated from protobuf field <code>string figi = 1;</code>
     * @return string
     */
    public function getFigi()
    {
        return $this->figi;
    }

    /**
     * Figi-идентификатор инструмента
     *
     * Generated from protobuf field <code>string figi = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFigi($var)
    {
        GPBUtil::checkString($var, True);
        $this->figi = $var;

        return $this;
    }

    /**
     * Тикер инструмента
     *
     * Generated from protobuf field <code>string ticker = 2;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     * Тикер инструмента
     *
     * Generated from protobuf field <code>string ticker = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     * Класс-код инструмента
     *
     * Generated from protobuf field <code>string class_code = 3;</code>
     * @return string
     */
    public function getClassCode()
    {
        return $this->class_code;
    }

    /**
     * Класс-код инструмента
     *
     * Generated from protobuf field <code>string class_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClassCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_code = $var;

        return $this;
    }

    /**
     * Валюта расчётов
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Валюта расчётов
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentType instrument_kind = 10;</code>
     * @return int
     */
    public function getInstrumentKind()
    {
        return $this->instrument_kind;
    }

    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentType instrument_kind = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setInstrumentKind($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\InstrumentType::class);
        $this->instrument_kind = $var;

        return $this;
    }

    /**
     * Название инструмента
     *
     * Generated from protobuf field <code>string name = 12;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Название инструмента
     *
     * Generated from protobuf field <code>string name = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Tорговая площадка (секция биржи)
     *
     * Generated from protobuf field <code>string exchange = 13;</code>
     * @return string
     */
    public function getExchange()
    {
        return $this->exchange;
    }

    /**
     * Tорговая площадка (секция биржи)
     *
     * Generated from protobuf field <code>string exchange = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setExchange($var)
    {
        GPBUtil::checkString($var, True);
        $this->exchange = $var;

        return $this;
    }

    /**
     * Уникальный идентификатор инструмента
     *
     * Generated from protobuf field <code>string uid = 14;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Уникальный идентификатор инструмента
     *
     * Generated from protobuf field <code>string uid = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * Признак доступности для покупки
     *
     * Generated from protobuf field <code>bool buy_available_flag = 404;</code>
     * @return bool
     */
    public function getBuyAvailableFlag()
    {
        return $this->buy_available_flag;
    }

    /**
     * Признак доступности для покупки
     *
     * Generated from protobuf field <code>bool buy_available_flag = 404;</code>
     * @param bool $var
     * @return $this
     */
    public function setBuyAvailableFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->buy_available_flag = $var;

        return $this;
    }

    /**
     * Признак доступности для продажи
     *
     * Generated from protobuf field <code>bool sell_available_flag = 405;</code>
     * @return bool
     */
    public function getSellAvailableFlag()
    {
        return $this->sell_available_flag;
    }

    /**
     * Признак доступности для продажи
     *
     * Generated from protobuf field <code>bool sell_available_flag = 405;</code>
     * @param bool $var
     * @return $this
     */
    public function setSellAvailableFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->sell_available_flag = $var;

        return $this;
    }

}

