<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Запрос получения инструмента по идентификатору.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.InstrumentRequest</code>
 */
class InstrumentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Тип идентификатора инструмента. Возможные значения: figi, ticker, isin. Подробнее об идентификации инструментов: [Идентификация инструментов](/investAPI/faq_identification/)
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentIdType id_type = 1;</code>
     */
    protected $id_type = 0;
    /**
     * Идентификатор class_code. Обязателен при id_type = ticker.
     *
     * Generated from protobuf field <code>string class_code = 2;</code>
     */
    protected $class_code = '';
    /**
     * Идентификатор запрашиваемого инструмента.
     *
     * Generated from protobuf field <code>string id = 3;</code>
     */
    protected $id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id_type
     *           Тип идентификатора инструмента. Возможные значения: figi, ticker, isin. Подробнее об идентификации инструментов: [Идентификация инструментов](/investAPI/faq_identification/)
     *     @type string $class_code
     *           Идентификатор class_code. Обязателен при id_type = ticker.
     *     @type string $id
     *           Идентификатор запрашиваемого инструмента.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Тип идентификатора инструмента. Возможные значения: figi, ticker, isin. Подробнее об идентификации инструментов: [Идентификация инструментов](/investAPI/faq_identification/)
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentIdType id_type = 1;</code>
     * @return int
     */
    public function getIdType()
    {
        return $this->id_type;
    }

    /**
     * Тип идентификатора инструмента. Возможные значения: figi, ticker, isin. Подробнее об идентификации инструментов: [Идентификация инструментов](/investAPI/faq_identification/)
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentIdType id_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIdType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\InstrumentIdType::class);
        $this->id_type = $var;

        return $this;
    }

    /**
     * Идентификатор class_code. Обязателен при id_type = ticker.
     *
     * Generated from protobuf field <code>string class_code = 2;</code>
     * @return string
     */
    public function getClassCode()
    {
        return $this->class_code;
    }

    /**
     * Идентификатор class_code. Обязателен при id_type = ticker.
     *
     * Generated from protobuf field <code>string class_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClassCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_code = $var;

        return $this;
    }

    /**
     * Идентификатор запрашиваемого инструмента.
     *
     * Generated from protobuf field <code>string id = 3;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Идентификатор запрашиваемого инструмента.
     *
     * Generated from protobuf field <code>string id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

