<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Данные по инструменту.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.InstrumentResponse</code>
 */
class InstrumentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Основная информация об инструменте.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Instrument instrument = 1;</code>
     */
    protected $instrument = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\Instrument $instrument
     *           Основная информация об инструменте.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Основная информация об инструменте.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Instrument instrument = 1;</code>
     * @return \Tinkoff\Invest\V1\Instrument|null
     */
    public function getInstrument()
    {
        return $this->instrument;
    }

    public function hasInstrument()
    {
        return isset($this->instrument);
    }

    public function clearInstrument()
    {
        unset($this->instrument);
    }

    /**
     * Основная информация об инструменте.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Instrument instrument = 1;</code>
     * @param \Tinkoff\Invest\V1\Instrument $var
     * @return $this
     */
    public function setInstrument($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Instrument::class);
        $this->instrument = $var;

        return $this;
    }

}

