<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketdata.proto

namespace Tinkoff\Invest\V1;

use UnexpectedValueException;

/**
 *Тип последней цены
 *
 * Protobuf type <code>tinkoff.public.invest.api.contract.v1.LastPriceType</code>
 */
class LastPriceType
{
    /**
     *Не определен.
     *
     * Generated from protobuf enum <code>LAST_PRICE_UNSPECIFIED = 0;</code>
     */
    const LAST_PRICE_UNSPECIFIED = 0;
    /**
     * Цена биржи.
     *
     * Generated from protobuf enum <code>LAST_PRICE_EXCHANGE = 1;</code>
     */
    const LAST_PRICE_EXCHANGE = 1;
    /**
     * Цена дилера
     *
     * Generated from protobuf enum <code>LAST_PRICE_DEALER = 2;</code>
     */
    const LAST_PRICE_DEALER = 2;

    private static $valueToName = [
        self::LAST_PRICE_UNSPECIFIED => 'LAST_PRICE_UNSPECIFIED',
        self::LAST_PRICE_EXCHANGE => 'LAST_PRICE_EXCHANGE',
        self::LAST_PRICE_DEALER => 'LAST_PRICE_DEALER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

