<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: operations.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Массив с информацией о сделках.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.OperationItemTrades</code>
 */
class OperationItemTrades extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.OperationItemTrade trades = 6;</code>
     */
    private $trades;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\OperationItemTrade[] $trades
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.OperationItemTrade trades = 6;</code>
     * @return RepeatedField<\Tinkoff\Invest\V1\OperationItemTrade>
     */
    public function getTrades()
    {
        return $this->trades;
    }

    /**
     * Generated from protobuf field <code>repeated .tinkoff.public.invest.api.contract.v1.OperationItemTrade trades = 6;</code>
     * @param \Tinkoff\Invest\V1\OperationItemTrade[] $var
     * @return $this
     */
    public function setTrades($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tinkoff\Invest\V1\OperationItemTrade::class);
        $this->trades = $arr;

        return $this;
    }

}

