<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: operations.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *Данные об операции.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.OperationData</code>
 */
class OperationData extends \Google\Protobuf\Internal\Message
{
    /**
     *Идентификатор счета.
     *
     * Generated from protobuf field <code>string broker_account_id = 1;</code>
     */
    protected $broker_account_id = '';
    /**
     *Номер поручения.
     *
     * Generated from protobuf field <code>string id = 2;</code>
     */
    protected $id = '';
    /**
     *Номер родительского поручения.
     *
     * Generated from protobuf field <code>string parent_operation_id = 3;</code>
     */
    protected $parent_operation_id = '';
    /**
     *Название инструмента.
     *
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     *Дата.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp date = 5;</code>
     */
    protected $date = null;
    /**
     *Тип операции.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OperationType type = 6;</code>
     */
    protected $type = 0;
    /**
     *Статус поручения.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OperationState state = 7;</code>
     */
    protected $state = 0;
    /**
     *Уникальный идентификатор инструмента.
     *
     * Generated from protobuf field <code>string instrument_uid = 8;</code>
     */
    protected $instrument_uid = '';
    /**
     *FIGI-идентификатор инструмента.
     *
     * Generated from protobuf field <code>string figi = 9;</code>
     */
    protected $figi = '';
    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>string instrument_type = 10;</code>
     */
    protected $instrument_type = '';
    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentType instrument_kind = 11;</code>
     */
    protected $instrument_kind = 0;
    /**
     *Идентификатор позиции.
     *
     * Generated from protobuf field <code>string position_uid = 12;</code>
     */
    protected $position_uid = '';
    /**
     *Тикер инструмента.
     *
     * Generated from protobuf field <code>string ticker = 13;</code>
     */
    protected $ticker = '';
    /**
     *Класс-код (секция торгов).
     *
     * Generated from protobuf field <code>string class_code = 14;</code>
     */
    protected $class_code = '';
    /**
     *Сумма операции.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.MoneyValue payment = 15;</code>
     */
    protected $payment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $broker_account_id
     *          Идентификатор счета.
     *     @type string $id
     *          Номер поручения.
     *     @type string $parent_operation_id
     *          Номер родительского поручения.
     *     @type string $name
     *          Название инструмента.
     *     @type \Google\Protobuf\Timestamp $date
     *          Дата.
     *     @type int $type
     *          Тип операции.
     *     @type int $state
     *          Статус поручения.
     *     @type string $instrument_uid
     *          Уникальный идентификатор инструмента.
     *     @type string $figi
     *          FIGI-идентификатор инструмента.
     *     @type string $instrument_type
     *          Тип инструмента.
     *     @type int $instrument_kind
     *          Тип инструмента.
     *     @type string $position_uid
     *          Идентификатор позиции.
     *     @type string $ticker
     *          Тикер инструмента.
     *     @type string $class_code
     *          Класс-код (секция торгов).
     *     @type \Tinkoff\Invest\V1\MoneyValue $payment
     *          Сумма операции.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     *Идентификатор счета.
     *
     * Generated from protobuf field <code>string broker_account_id = 1;</code>
     * @return string
     */
    public function getBrokerAccountId()
    {
        return $this->broker_account_id;
    }

    /**
     *Идентификатор счета.
     *
     * Generated from protobuf field <code>string broker_account_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBrokerAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->broker_account_id = $var;

        return $this;
    }

    /**
     *Номер поручения.
     *
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *Номер поручения.
     *
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     *Номер родительского поручения.
     *
     * Generated from protobuf field <code>string parent_operation_id = 3;</code>
     * @return string
     */
    public function getParentOperationId()
    {
        return $this->parent_operation_id;
    }

    /**
     *Номер родительского поручения.
     *
     * Generated from protobuf field <code>string parent_operation_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParentOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_operation_id = $var;

        return $this;
    }

    /**
     *Название инструмента.
     *
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *Название инструмента.
     *
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *Дата.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp date = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDate()
    {
        return $this->date;
    }

    public function hasDate()
    {
        return isset($this->date);
    }

    public function clearDate()
    {
        unset($this->date);
    }

    /**
     *Дата.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp date = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date = $var;

        return $this;
    }

    /**
     *Тип операции.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OperationType type = 6;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *Тип операции.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OperationType type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\OperationType::class);
        $this->type = $var;

        return $this;
    }

    /**
     *Статус поручения.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OperationState state = 7;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     *Статус поручения.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OperationState state = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\OperationState::class);
        $this->state = $var;

        return $this;
    }

    /**
     *Уникальный идентификатор инструмента.
     *
     * Generated from protobuf field <code>string instrument_uid = 8;</code>
     * @return string
     */
    public function getInstrumentUid()
    {
        return $this->instrument_uid;
    }

    /**
     *Уникальный идентификатор инструмента.
     *
     * Generated from protobuf field <code>string instrument_uid = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setInstrumentUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->instrument_uid = $var;

        return $this;
    }

    /**
     *FIGI-идентификатор инструмента.
     *
     * Generated from protobuf field <code>string figi = 9;</code>
     * @return string
     */
    public function getFigi()
    {
        return $this->figi;
    }

    /**
     *FIGI-идентификатор инструмента.
     *
     * Generated from protobuf field <code>string figi = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFigi($var)
    {
        GPBUtil::checkString($var, True);
        $this->figi = $var;

        return $this;
    }

    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>string instrument_type = 10;</code>
     * @return string
     */
    public function getInstrumentType()
    {
        return $this->instrument_type;
    }

    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>string instrument_type = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setInstrumentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->instrument_type = $var;

        return $this;
    }

    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentType instrument_kind = 11;</code>
     * @return int
     */
    public function getInstrumentKind()
    {
        return $this->instrument_kind;
    }

    /**
     *Тип инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.InstrumentType instrument_kind = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setInstrumentKind($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\InstrumentType::class);
        $this->instrument_kind = $var;

        return $this;
    }

    /**
     *Идентификатор позиции.
     *
     * Generated from protobuf field <code>string position_uid = 12;</code>
     * @return string
     */
    public function getPositionUid()
    {
        return $this->position_uid;
    }

    /**
     *Идентификатор позиции.
     *
     * Generated from protobuf field <code>string position_uid = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPositionUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->position_uid = $var;

        return $this;
    }

    /**
     *Тикер инструмента.
     *
     * Generated from protobuf field <code>string ticker = 13;</code>
     * @return string
     */
    public function getTicker()
    {
        return $this->ticker;
    }

    /**
     *Тикер инструмента.
     *
     * Generated from protobuf field <code>string ticker = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTicker($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticker = $var;

        return $this;
    }

    /**
     *Класс-код (секция торгов).
     *
     * Generated from protobuf field <code>string class_code = 14;</code>
     * @return string
     */
    public function getClassCode()
    {
        return $this->class_code;
    }

    /**
     *Класс-код (секция торгов).
     *
     * Generated from protobuf field <code>string class_code = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setClassCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_code = $var;

        return $this;
    }

    /**
     *Сумма операции.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.MoneyValue payment = 15;</code>
     * @return \Tinkoff\Invest\V1\MoneyValue|null
     */
    public function getPayment()
    {
        return $this->payment;
    }

    public function hasPayment()
    {
        return isset($this->payment);
    }

    public function clearPayment()
    {
        unset($this->payment);
    }

    /**
     *Сумма операции.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.MoneyValue payment = 15;</code>
     * @param \Tinkoff\Invest\V1\MoneyValue $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\MoneyValue::class);
        $this->payment = $var;

        return $this;
    }

}

