<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Tinkoff\Invest\V1;

use UnexpectedValueException;

/**
 *Тип идентификатора заявки
 *
 * Protobuf type <code>tinkoff.public.invest.api.contract.v1.OrderIdType</code>
 */
class OrderIdType
{
    /**
     *Тип идентификатора не указан.
     *
     * Generated from protobuf enum <code>ORDER_ID_TYPE_UNSPECIFIED = 0;</code>
     */
    const ORDER_ID_TYPE_UNSPECIFIED = 0;
    /**
     *Биржевой идентификатор
     *
     * Generated from protobuf enum <code>ORDER_ID_TYPE_EXCHANGE = 1;</code>
     */
    const ORDER_ID_TYPE_EXCHANGE = 1;
    /**
     *Ключ идемпотентности, переданный клиентом
     *
     * Generated from protobuf enum <code>ORDER_ID_TYPE_REQUEST = 2;</code>
     */
    const ORDER_ID_TYPE_REQUEST = 2;

    private static $valueToName = [
        self::ORDER_ID_TYPE_UNSPECIFIED => 'ORDER_ID_TYPE_UNSPECIFIED',
        self::ORDER_ID_TYPE_EXCHANGE => 'ORDER_ID_TYPE_EXCHANGE',
        self::ORDER_ID_TYPE_REQUEST => 'ORDER_ID_TYPE_REQUEST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

