<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.Page</code>
 */
class Page extends \Google\Protobuf\Internal\Message
{
    /**
     *Максимальное число возвращаемых записей.
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     */
    protected $limit = 0;
    /**
     *Порядковый номер страницы, начиная с 0.
     *
     * Generated from protobuf field <code>int32 page_number = 2;</code>
     */
    protected $page_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $limit
     *          Максимальное число возвращаемых записей.
     *     @type int $page_number
     *          Порядковый номер страницы, начиная с 0.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     *Максимальное число возвращаемых записей.
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     *Максимальное число возвращаемых записей.
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     *Порядковый номер страницы, начиная с 0.
     *
     * Generated from protobuf field <code>int32 page_number = 2;</code>
     * @return int
     */
    public function getPageNumber()
    {
        return $this->page_number;
    }

    /**
     *Порядковый номер страницы, начиная с 0.
     *
     * Generated from protobuf field <code>int32 page_number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_number = $var;

        return $this;
    }

}

