<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operations.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Баланс фьючерса.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.PositionsFutures</code>
 */
class PositionsFutures extends \Google\Protobuf\Internal\Message
{
    /**
     *Figi-идентификатор фьючерса.
     *
     * Generated from protobuf field <code>string figi = 1;</code>
     */
    protected $figi = '';
    /**
     *Количество бумаг заблокированных выставленными заявками.
     *
     * Generated from protobuf field <code>int64 blocked = 2;</code>
     */
    protected $blocked = 0;
    /**
     *Текущий незаблокированный баланс.
     *
     * Generated from protobuf field <code>int64 balance = 3;</code>
     */
    protected $balance = 0;
    /**
     *Уникальный идентификатор позиции.
     *
     * Generated from protobuf field <code>string position_uid = 4;</code>
     */
    protected $position_uid = '';
    /**
     *Уникальный идентификатор  инструмента.
     *
     * Generated from protobuf field <code>string instrument_uid = 5;</code>
     */
    protected $instrument_uid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $figi
     *          Figi-идентификатор фьючерса.
     *     @type int|string $blocked
     *          Количество бумаг заблокированных выставленными заявками.
     *     @type int|string $balance
     *          Текущий незаблокированный баланс.
     *     @type string $position_uid
     *          Уникальный идентификатор позиции.
     *     @type string $instrument_uid
     *          Уникальный идентификатор  инструмента.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     *Figi-идентификатор фьючерса.
     *
     * Generated from protobuf field <code>string figi = 1;</code>
     * @return string
     */
    public function getFigi()
    {
        return $this->figi;
    }

    /**
     *Figi-идентификатор фьючерса.
     *
     * Generated from protobuf field <code>string figi = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFigi($var)
    {
        GPBUtil::checkString($var, True);
        $this->figi = $var;

        return $this;
    }

    /**
     *Количество бумаг заблокированных выставленными заявками.
     *
     * Generated from protobuf field <code>int64 blocked = 2;</code>
     * @return int|string
     */
    public function getBlocked()
    {
        return $this->blocked;
    }

    /**
     *Количество бумаг заблокированных выставленными заявками.
     *
     * Generated from protobuf field <code>int64 blocked = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlocked($var)
    {
        GPBUtil::checkInt64($var);
        $this->blocked = $var;

        return $this;
    }

    /**
     *Текущий незаблокированный баланс.
     *
     * Generated from protobuf field <code>int64 balance = 3;</code>
     * @return int|string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     *Текущий незаблокированный баланс.
     *
     * Generated from protobuf field <code>int64 balance = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     *Уникальный идентификатор позиции.
     *
     * Generated from protobuf field <code>string position_uid = 4;</code>
     * @return string
     */
    public function getPositionUid()
    {
        return $this->position_uid;
    }

    /**
     *Уникальный идентификатор позиции.
     *
     * Generated from protobuf field <code>string position_uid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPositionUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->position_uid = $var;

        return $this;
    }

    /**
     *Уникальный идентификатор  инструмента.
     *
     * Generated from protobuf field <code>string instrument_uid = 5;</code>
     * @return string
     */
    public function getInstrumentUid()
    {
        return $this->instrument_uid;
    }

    /**
     *Уникальный идентификатор  инструмента.
     *
     * Generated from protobuf field <code>string instrument_uid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInstrumentUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->instrument_uid = $var;

        return $this;
    }

}

