<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stoporders.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Запрос выставления стоп-заявки.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.PostStopOrderRequest</code>
 */
class PostStopOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *Deprecated Figi-идентификатор инструмента. Необходимо использовать instrument_id.
     *
     * Generated from protobuf field <code>string figi = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $figi = null;
    /**
     *Количество лотов
     *
     * Generated from protobuf field <code>int64 quantity = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $quantity = 0;
    /**
     *Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation price = 3;</code>
     */
    protected $price = null;
    /**
     *Стоп-цена заявки за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation stop_price = 4;</code>
     */
    protected $stop_price = null;
    /**
     *Направление операции
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderDirection direction = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $direction = 0;
    /**
     *Номер счёта
     *
     * Generated from protobuf field <code>string account_id = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $account_id = '';
    /**
     *Тип экспирации заявки
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderExpirationType expiration_type = 7 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $expiration_type = 0;
    /**
     *Тип заявки
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderType stop_order_type = 8 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $stop_order_type = 0;
    /**
     *Дата и время окончания действия стоп-заявки в часовом поясе UTC. **Для ExpirationType = GoodTillDate заполнение обязательно, для GoodTillCancel игнорируется**.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp expire_date = 9;</code>
     */
    protected $expire_date = null;
    /**
     *Идентификатор инструмента, принимает значения Figi или instrument_uid.
     *
     * Generated from protobuf field <code>string instrument_id = 10 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instrument_id = '';
    /**
     *Тип дочерней биржевой заявки для тейкпрофита
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.ExchangeOrderType exchange_order_type = 11;</code>
     */
    protected $exchange_order_type = 0;
    /**
     *Подтип стоп-заявки TakeProfit
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.TakeProfitType take_profit_type = 12;</code>
     */
    protected $take_profit_type = 0;
    /**
     *Массив с параметрами трейлинг-стопа
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PostStopOrderRequest.TrailingData trailing_data = 13;</code>
     */
    protected $trailing_data = null;
    /**
     *Тип цены
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 14;</code>
     */
    protected $price_type = 0;
    /**
     *Идентификатор запроса выставления поручения для целей идемпотентности в формате UID. Максимальная длина 36 символов.
     *
     * Generated from protobuf field <code>string order_id = 15 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $order_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $figi
     *          Deprecated Figi-идентификатор инструмента. Необходимо использовать instrument_id.
     *     @type int|string $quantity
     *          Количество лотов
     *     @type \Tinkoff\Invest\V1\Quotation $price
     *          Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *     @type \Tinkoff\Invest\V1\Quotation $stop_price
     *          Стоп-цена заявки за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *     @type int $direction
     *          Направление операции
     *     @type string $account_id
     *          Номер счёта
     *     @type int $expiration_type
     *          Тип экспирации заявки
     *     @type int $stop_order_type
     *          Тип заявки
     *     @type \Google\Protobuf\Timestamp $expire_date
     *          Дата и время окончания действия стоп-заявки в часовом поясе UTC. **Для ExpirationType = GoodTillDate заполнение обязательно, для GoodTillCancel игнорируется**.
     *     @type string $instrument_id
     *          Идентификатор инструмента, принимает значения Figi или instrument_uid.
     *     @type int $exchange_order_type
     *          Тип дочерней биржевой заявки для тейкпрофита
     *     @type int $take_profit_type
     *          Подтип стоп-заявки TakeProfit
     *     @type \Tinkoff\Invest\V1\PostStopOrderRequest\TrailingData $trailing_data
     *          Массив с параметрами трейлинг-стопа
     *     @type int $price_type
     *          Тип цены
     *     @type string $order_id
     *          Идентификатор запроса выставления поручения для целей идемпотентности в формате UID. Максимальная длина 36 символов.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Stoporders::initOnce();
        parent::__construct($data);
    }

    /**
     *Deprecated Figi-идентификатор инструмента. Необходимо использовать instrument_id.
     *
     * Generated from protobuf field <code>string figi = 1 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getFigi()
    {
        @trigger_error('figi is deprecated.', E_USER_DEPRECATED);
        return isset($this->figi) ? $this->figi : '';
    }

    public function hasFigi()
    {
        @trigger_error('figi is deprecated.', E_USER_DEPRECATED);
        return isset($this->figi);
    }

    public function clearFigi()
    {
        @trigger_error('figi is deprecated.', E_USER_DEPRECATED);
        unset($this->figi);
    }

    /**
     *Deprecated Figi-идентификатор инструмента. Необходимо использовать instrument_id.
     *
     * Generated from protobuf field <code>string figi = 1 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setFigi($var)
    {
        @trigger_error('figi is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->figi = $var;

        return $this;
    }

    /**
     *Количество лотов
     *
     * Generated from protobuf field <code>int64 quantity = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int|string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     *Количество лотов
     *
     * Generated from protobuf field <code>int64 quantity = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     *Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation price = 3;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getPrice()
    {
        return isset($this->price) ? $this->price : null;
    }

    public function hasPrice()
    {
        return isset($this->price);
    }

    public function clearPrice()
    {
        unset($this->price);
    }

    /**
     *Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation price = 3;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->price = $var;

        return $this;
    }

    /**
     *Стоп-цена заявки за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation stop_price = 4;</code>
     * @return \Tinkoff\Invest\V1\Quotation|null
     */
    public function getStopPrice()
    {
        return isset($this->stop_price) ? $this->stop_price : null;
    }

    public function hasStopPrice()
    {
        return isset($this->stop_price);
    }

    public function clearStopPrice()
    {
        unset($this->stop_price);
    }

    /**
     *Стоп-цена заявки за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Quotation stop_price = 4;</code>
     * @param \Tinkoff\Invest\V1\Quotation $var
     * @return $this
     */
    public function setStopPrice($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Quotation::class);
        $this->stop_price = $var;

        return $this;
    }

    /**
     *Направление операции
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderDirection direction = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     *Направление операции
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderDirection direction = 5 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\StopOrderDirection::class);
        $this->direction = $var;

        return $this;
    }

    /**
     *Номер счёта
     *
     * Generated from protobuf field <code>string account_id = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     *Номер счёта
     *
     * Generated from protobuf field <code>string account_id = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     *Тип экспирации заявки
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderExpirationType expiration_type = 7 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int
     */
    public function getExpirationType()
    {
        return $this->expiration_type;
    }

    /**
     *Тип экспирации заявки
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderExpirationType expiration_type = 7 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int $var
     * @return $this
     */
    public function setExpirationType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\StopOrderExpirationType::class);
        $this->expiration_type = $var;

        return $this;
    }

    /**
     *Тип заявки
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderType stop_order_type = 8 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return int
     */
    public function getStopOrderType()
    {
        return $this->stop_order_type;
    }

    /**
     *Тип заявки
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.StopOrderType stop_order_type = 8 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int $var
     * @return $this
     */
    public function setStopOrderType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\StopOrderType::class);
        $this->stop_order_type = $var;

        return $this;
    }

    /**
     *Дата и время окончания действия стоп-заявки в часовом поясе UTC. **Для ExpirationType = GoodTillDate заполнение обязательно, для GoodTillCancel игнорируется**.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp expire_date = 9;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getExpireDate()
    {
        return isset($this->expire_date) ? $this->expire_date : null;
    }

    public function hasExpireDate()
    {
        return isset($this->expire_date);
    }

    public function clearExpireDate()
    {
        unset($this->expire_date);
    }

    /**
     *Дата и время окончания действия стоп-заявки в часовом поясе UTC. **Для ExpirationType = GoodTillDate заполнение обязательно, для GoodTillCancel игнорируется**.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp expire_date = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setExpireDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->expire_date = $var;

        return $this;
    }

    /**
     *Идентификатор инструмента, принимает значения Figi или instrument_uid.
     *
     * Generated from protobuf field <code>string instrument_id = 10 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getInstrumentId()
    {
        return $this->instrument_id;
    }

    /**
     *Идентификатор инструмента, принимает значения Figi или instrument_uid.
     *
     * Generated from protobuf field <code>string instrument_id = 10 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setInstrumentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->instrument_id = $var;

        return $this;
    }

    /**
     *Тип дочерней биржевой заявки для тейкпрофита
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.ExchangeOrderType exchange_order_type = 11;</code>
     * @return int
     */
    public function getExchangeOrderType()
    {
        return $this->exchange_order_type;
    }

    /**
     *Тип дочерней биржевой заявки для тейкпрофита
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.ExchangeOrderType exchange_order_type = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setExchangeOrderType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\ExchangeOrderType::class);
        $this->exchange_order_type = $var;

        return $this;
    }

    /**
     *Подтип стоп-заявки TakeProfit
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.TakeProfitType take_profit_type = 12;</code>
     * @return int
     */
    public function getTakeProfitType()
    {
        return $this->take_profit_type;
    }

    /**
     *Подтип стоп-заявки TakeProfit
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.TakeProfitType take_profit_type = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setTakeProfitType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\TakeProfitType::class);
        $this->take_profit_type = $var;

        return $this;
    }

    /**
     *Массив с параметрами трейлинг-стопа
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PostStopOrderRequest.TrailingData trailing_data = 13;</code>
     * @return \Tinkoff\Invest\V1\PostStopOrderRequest\TrailingData|null
     */
    public function getTrailingData()
    {
        return isset($this->trailing_data) ? $this->trailing_data : null;
    }

    public function hasTrailingData()
    {
        return isset($this->trailing_data);
    }

    public function clearTrailingData()
    {
        unset($this->trailing_data);
    }

    /**
     *Массив с параметрами трейлинг-стопа
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PostStopOrderRequest.TrailingData trailing_data = 13;</code>
     * @param \Tinkoff\Invest\V1\PostStopOrderRequest\TrailingData $var
     * @return $this
     */
    public function setTrailingData($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\PostStopOrderRequest\TrailingData::class);
        $this->trailing_data = $var;

        return $this;
    }

    /**
     *Тип цены
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 14;</code>
     * @return int
     */
    public function getPriceType()
    {
        return $this->price_type;
    }

    /**
     *Тип цены
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.PriceType price_type = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setPriceType($var)
    {
        GPBUtil::checkEnum($var, \Tinkoff\Invest\V1\PriceType::class);
        $this->price_type = $var;

        return $this;
    }

    /**
     *Идентификатор запроса выставления поручения для целей идемпотентности в формате UID. Максимальная длина 36 символов.
     *
     * Generated from protobuf field <code>string order_id = 15 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     *Идентификатор запроса выставления поручения для целей идемпотентности в формате UID. Максимальная длина 36 символов.
     *
     * Generated from protobuf field <code>string order_id = 15 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

}

