<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Запрос ставок риска
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.RiskRatesRequest</code>
 */
class RiskRatesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Идентификаторы инструментов.
     *
     * Generated from protobuf field <code>repeated string instrument_id = 1;</code>
     */
    private $instrument_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $instrument_id
     *           Идентификаторы инструментов.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Instruments::initOnce();
        parent::__construct($data);
    }

    /**
     * Идентификаторы инструментов.
     *
     * Generated from protobuf field <code>repeated string instrument_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInstrumentId()
    {
        return $this->instrument_id;
    }

    /**
     * Идентификаторы инструментов.
     *
     * Generated from protobuf field <code>repeated string instrument_id = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInstrumentId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->instrument_id = $arr;

        return $this;
    }

}

