<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

use UnexpectedValueException;

/**
 *Уровень риска облигации.
 *
 * Protobuf type <code>tinkoff.public.invest.api.contract.v1.RiskLevel</code>
 */
class RiskLevel
{
    /**
     *Высокий уровень риска
     *
     * Generated from protobuf enum <code>RISK_LEVEL_HIGH = 0;</code>
     */
    const RISK_LEVEL_HIGH = 0;
    /**
     *Средний уровень риска
     *
     * Generated from protobuf enum <code>RISK_LEVEL_MODERATE = 1;</code>
     */
    const RISK_LEVEL_MODERATE = 1;
    /**
     *Низкий уровень риска
     *
     * Generated from protobuf enum <code>RISK_LEVEL_LOW = 2;</code>
     */
    const RISK_LEVEL_LOW = 2;

    private static $valueToName = [
        self::RISK_LEVEL_HIGH => 'RISK_LEVEL_HIGH',
        self::RISK_LEVEL_MODERATE => 'RISK_LEVEL_MODERATE',
        self::RISK_LEVEL_LOW => 'RISK_LEVEL_LOW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

