<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

if (false) {
    /**
     * This class is deprecated. Use Tinkoff\Invest\V1\StructuredNote\LogicPortfolio instead.
     * @deprecated
     */
    class StructuredNote_LogicPortfolio {}
}
class_exists(StructuredNote\LogicPortfolio::class);
@trigger_error('Tinkoff\Invest\V1\StructuredNote_LogicPortfolio is deprecated and will be removed in the next major release. Use Tinkoff\Invest\V1\StructuredNote\LogicPortfolio instead', E_USER_DEPRECATED);

