<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruments.proto

namespace Tinkoff\Invest\V1;

if (false) {
    /**
     * This class is deprecated. Use Tinkoff\Invest\V1\StructuredNote\Yield instead.
     * @deprecated
     */
    class StructuredNote_Yield {}
}
class_exists(StructuredNote\Yield::class);
@trigger_error('Tinkoff\Invest\V1\StructuredNote_Yield is deprecated and will be removed in the next major release. Use Tinkoff\Invest\V1\StructuredNote\Yield instead', E_USER_DEPRECATED);

