<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Tinkoff\Invest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Информация о торговых поручениях.
 *
 * Generated from protobuf message <code>tinkoff.public.invest.api.contract.v1.TradesStreamResponse</code>
 */
class TradesStreamResponse extends \Google\Protobuf\Internal\Message
{
    protected $payload;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Tinkoff\Invest\V1\OrderTrades $order_trades
     *          Информация об исполнении торгового поручения.
     *     @type \Tinkoff\Invest\V1\Ping $ping
     *          Проверка активности стрима.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     *Информация об исполнении торгового поручения.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OrderTrades order_trades = 1;</code>
     * @return \Tinkoff\Invest\V1\OrderTrades|null
     */
    public function getOrderTrades()
    {
        return $this->readOneof(1);
    }

    public function hasOrderTrades()
    {
        return $this->hasOneof(1);
    }

    /**
     *Информация об исполнении торгового поручения.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.OrderTrades order_trades = 1;</code>
     * @param \Tinkoff\Invest\V1\OrderTrades $var
     * @return $this
     */
    public function setOrderTrades($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\OrderTrades::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     *Проверка активности стрима.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Ping ping = 2;</code>
     * @return \Tinkoff\Invest\V1\Ping|null
     */
    public function getPing()
    {
        return $this->readOneof(2);
    }

    public function hasPing()
    {
        return $this->hasOneof(2);
    }

    /**
     *Проверка активности стрима.
     *
     * Generated from protobuf field <code>.tinkoff.public.invest.api.contract.v1.Ping ping = 2;</code>
     * @param \Tinkoff\Invest\V1\Ping $var
     * @return $this
     */
    public function setPing($var)
    {
        GPBUtil::checkMessage($var, \Tinkoff\Invest\V1\Ping::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPayload()
    {
        return $this->whichOneof("payload");
    }

}

